/* confdefs.h */
#define PACKAGE_NAME "dsock"
#define PACKAGE_TARNAME "dsock"
#define PACKAGE_VERSION "0.5-alpha-117-g1663bea"
#define PACKAGE_STRING "dsock 0.5-alpha-117-g1663bea"
#define PACKAGE_BUGREPORT "libmill@freelists.org"
#define PACKAGE_URL "http://libdill.org/"
#define PACKAGE "dsock"
#define VERSION "0.5-alpha-117-g1663bea"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_ERR_H 1
#define HAVE_ASPRINTF 1
#define HAVE_STRLCPY 1
#define HAVE_STRSEP 1
#define HAVE_TIMEGM 1
#define HAVE_ARC4RANDOM 1
#define HAVE_ARC4RANDOM_BUF 1
#define HAVE_ARC4RANDOM_UNIFORM 1
#define HAVE_GETENTROPY 1
#define HAVE_MKSTEMP 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
