import CDsock

let DSOCK_BTLS_DEFAULT  =
    DSOCK_BTLS_PROTO_DEFAULT |
    DSOCK_BTLS_DHEPARAMS_NONE |
    DSOCK_BTLS_ECDHECURVE_AUTO |
    DSOCK_BTLS_CIPHERS_DEFAULT |
    DSOCK_BTLS_VERIFY_DEPTH_DEFAULT |
    DSOCK_BTLS_PREFER_CIPHERS_SERVER |
    DSOCK_BTLS_CLEAR_KEYS
