import CBtls

let BTLS_DEFAULT  =
    BTLS_PROTO_DEFAULT |
    BTLS_DHEPARAMS_NONE |
    BTLS_ECDHECURVE_AUTO |
    BTLS_CIPHERS_DEFAULT |
    BTLS_VERIFY_DEPTH_DEFAULT |
    BTLS_PREFER_CIPHERS_SERVER |
    BTLS_CLEAR_KEYS
